export enum Paths {
  Home = '/',
  // eslint-disable-next-line max-len
  SearchedRides = '/searched-rides/:cityFrom/:countyFrom/:stateFrom/:latFrom/:lonFrom/:cityTo/:countyTo/:stateTo/:latTo/:lonTo/:date/:seatsAmount/:page',
  SearchedRideForPassenger = '/searched-ride/:rideId',
  OwnRideForDriver = '/my-ride/:rideId',
  OwnRecurrentRideForDriver = '/my-recurrent-ride/:rideId',
  OwnRides = '/own-rides/:page',
  UserProfile = '/profile/:userId/:page',
  ChooseRideType = '/choose-ride-type',
  MyRequests = '/my-requests/:page',
  PendingRequests = '/pending-requests/:page',
  AddSingularRide = '/add-singular-ride',
  AddRecurrentRide = '/add-recurrent-ride',
  EditSingularRide = '/edit-singular-ride/:rideId',
  EditRecurrentRide = '/edit-recurrent-ride/:rideId',
  EditFullSingularRide = '/edit-full-singular-ride/:rideId',
  EditPartialSingularRide = '/edit-partial-singular-ride/:rideId',
  AddComment = '/add-comment/:userId',
  Error = '/error',
  NotFound = '*',
}
